import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from "next-auth"
import { authOptions } from "@/lib/auth"
import { GeminiService } from "@/lib/gemini"
import { GoogleService } from "@/lib/google-api"
import { format } from 'date-fns'

export async function POST(req: NextRequest) {
    const session = await getServerSession(authOptions)

    // Parse body early to check for Demo Mode
    const body = await req.json()
    const { settings, isDemoMode } = body

    if (!isDemoMode && (!session || !session.accessToken)) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    try {
        const { geminiApiKey, calendarId, driveFolderId, spreadsheetId } = settings
        // mock agenda for now or extract from body if user inputs it?
        const agendaItems = [{ title: "修学旅行の積立について" }, { title: "来月の避難訓練の役割分担" }]

        // 1. Initialize Services
        const gemini = new GeminiService(geminiApiKey)
        // Pass undefined accessToken if demo mode (GoogleService should handle it)
        const google = new GoogleService(isDemoMode ? undefined : session?.accessToken)

        // 2. Fetch Data
        // Use primary calendar if not provided
        const calId = calendarId || 'primary'
        const events = await google.getCalendarEvents(calId)

        // 3. AI Processing
        const aiSummary = await gemini.generateMeetingSummary(events, agendaItems)
        const shortSummary = await gemini.generateShortSummary(agendaItems)

        // 4. Generate Doc Content
        const todayStr = format(new Date(), 'yyyyMMdd')
        const title = `${todayStr}_第X回学年会資料`
        const content = `
${format(new Date(), 'yyyy年MM月dd日')} 学年会資料

■ 議題
${agendaItems.map(i => `- ${i.title}`).join('\n')}

■ 今後2週間の予定と見通し
${aiSummary}

■ 行事予定 (直近)
${events.map((e: any) => `- ${e.start.date || e.start.dateTime}: ${e.summary}`).join('\n')}

__________________________
Generated by Gemini School Manager
    `.trim()

        // 5. Create Doc
        const docId = await google.createDoc(driveFolderId, title, content)
        const docUrl = isDemoMode ? "https://docs.google.com/document/d/mock-doc-id/edit" : `https://docs.google.com/document/d/${docId}/edit`

        // 6. Log to Sheet
        await google.appendToSheet(spreadsheetId, [
            format(new Date(), 'yyyy/MM/dd'),
            shortSummary,
            (session?.user?.name) || 'Demo User',
            docUrl
        ])

        return NextResponse.json({ success: true, docUrl, shortSummary })

    } catch (error: any) {
        console.error("Generation Error:", error)
        return NextResponse.json({ error: error.message }, { status: 500 })
    }
}
